/* ============================================================================
   HoopScout — data file (window.HOOPDATA)
   ----------------------------------------------------------------------------
   Rosters scraped from the official FIBA U17 World Cup 2026 team pages
   (Detailed view) on 28 Jun 2026: number, name, position, birth year,
   height (cm) and club for each player. These are the 12-man game rosters,
   which differ in places from the pre-tournament squad announcements.

   height is in CENTIMETRES. Stats are empty (gp:0) until game data is added.
   ========================================================================== */

window.HOOPDATA = {
  event: {
    name: "FIBA U17 Basketball World Cup 2026",
    short: "U17 World Cup 2026",
    id: 208545,
    city: "Istanbul, Türkiye",
    dates: "27 Jun – 5 Jul 2026",
    url: "https://www.fiba.basketball/en/events/fiba-u17-basketball-world-cup-2026"
  },
  groups: {
    A: ["italy","usa","france","japan"],
    B: ["cameroon","canada","lithuania","china"],
    C: ["new-zealand","slovenia","puerto-rico","turkiye"],
    D: ["venezuela","australia","serbia","cote-divoire"]
  },
  teams: [
    {
      "id": "italy",
      "name": "Italy",
      "code": "ITA",
      "group": "A",
      "count": 12,
      "rosterUrl": "https://www.fiba.basketball/en/events/fiba-u17-basketball-world-cup-2026/teams/italy#roster"
    },
    {
      "id": "usa",
      "name": "USA",
      "code": "USA",
      "group": "A",
      "count": 12,
      "rosterUrl": "https://www.fiba.basketball/en/events/fiba-u17-basketball-world-cup-2026/teams/usa#roster"
    },
    {
      "id": "france",
      "name": "France",
      "code": "FRA",
      "group": "A",
      "count": 12,
      "rosterUrl": "https://www.fiba.basketball/en/events/fiba-u17-basketball-world-cup-2026/teams/france#roster"
    },
    {
      "id": "japan",
      "name": "Japan",
      "code": "JPN",
      "group": "A",
      "count": 12,
      "rosterUrl": "https://www.fiba.basketball/en/events/fiba-u17-basketball-world-cup-2026/teams/japan#roster"
    },
    {
      "id": "cameroon",
      "name": "Cameroon",
      "code": "CMR",
      "group": "B",
      "count": 12,
      "rosterUrl": "https://www.fiba.basketball/en/events/fiba-u17-basketball-world-cup-2026/teams/cameroon#roster"
    },
    {
      "id": "canada",
      "name": "Canada",
      "code": "CAN",
      "group": "B",
      "count": 12,
      "rosterUrl": "https://www.fiba.basketball/en/events/fiba-u17-basketball-world-cup-2026/teams/canada#roster"
    },
    {
      "id": "lithuania",
      "name": "Lithuania",
      "code": "LTU",
      "group": "B",
      "count": 12,
      "rosterUrl": "https://www.fiba.basketball/en/events/fiba-u17-basketball-world-cup-2026/teams/lithuania#roster"
    },
    {
      "id": "china",
      "name": "China",
      "code": "CHN",
      "group": "B",
      "count": 12,
      "rosterUrl": "https://www.fiba.basketball/en/events/fiba-u17-basketball-world-cup-2026/teams/china#roster"
    },
    {
      "id": "new-zealand",
      "name": "New Zealand",
      "code": "NZL",
      "group": "C",
      "count": 12,
      "rosterUrl": "https://www.fiba.basketball/en/events/fiba-u17-basketball-world-cup-2026/teams/new-zealand#roster"
    },
    {
      "id": "slovenia",
      "name": "Slovenia",
      "code": "SLO",
      "group": "C",
      "count": 12,
      "rosterUrl": "https://www.fiba.basketball/en/events/fiba-u17-basketball-world-cup-2026/teams/slovenia#roster"
    },
    {
      "id": "puerto-rico",
      "name": "Puerto Rico",
      "code": "PUR",
      "group": "C",
      "count": 12,
      "rosterUrl": "https://www.fiba.basketball/en/events/fiba-u17-basketball-world-cup-2026/teams/puerto-rico#roster"
    },
    {
      "id": "turkiye",
      "name": "Türkiye",
      "code": "TUR",
      "group": "C",
      "count": 12,
      "rosterUrl": "https://www.fiba.basketball/en/events/fiba-u17-basketball-world-cup-2026/teams/turkiye#roster"
    },
    {
      "id": "venezuela",
      "name": "Venezuela",
      "code": "VEN",
      "group": "D",
      "count": 12,
      "rosterUrl": "https://www.fiba.basketball/en/events/fiba-u17-basketball-world-cup-2026/teams/venezuela#roster"
    },
    {
      "id": "australia",
      "name": "Australia",
      "code": "AUS",
      "group": "D",
      "count": 12,
      "rosterUrl": "https://www.fiba.basketball/en/events/fiba-u17-basketball-world-cup-2026/teams/australia#roster"
    },
    {
      "id": "serbia",
      "name": "Serbia",
      "code": "SRB",
      "group": "D",
      "count": 12,
      "rosterUrl": "https://www.fiba.basketball/en/events/fiba-u17-basketball-world-cup-2026/teams/serbia#roster"
    },
    {
      "id": "cote-divoire",
      "name": "Côte d'Ivoire",
      "code": "CIV",
      "group": "D",
      "count": 12,
      "rosterUrl": "https://www.fiba.basketball/en/events/fiba-u17-basketball-world-cup-2026/teams/cote-divoire#roster"
    }
  ],
  players: [
    {"id":"italy-1","teamId":"italy","number":1,"name":"Jacopo Vogogna","pos":"G","height":194,"birthYear":2009,"club":"Olimpia Milano (ITA)","stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"italy-2","teamId":"italy","number":2,"name":"Leonardo Nicolodi","pos":"F","height":198,"birthYear":2009,"club":"Olimpia Milano (ITA)","stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"italy-4","teamId":"italy","number":4,"name":"Lapo Santini","pos":"F","height":202,"birthYear":2009,"club":"Orange 1 Basket Bassano (ITA)","stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"italy-8","teamId":"italy","number":8,"name":"Mattia Ruggeri","pos":"F","height":205,"birthYear":2009,"club":"Basket Santarcangelo SSDRL (ITA)","stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"italy-10","teamId":"italy","number":10,"name":"Simone Ventura","pos":"F","height":199,"birthYear":2009,"club":"Acqua S.Bernardo Cantu (ITA)","stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"italy-11","teamId":"italy","number":11,"name":"Cristian Malano","pos":"G","height":189,"birthYear":2009,"club":"Vis 2008 Ferrara (ITA)","stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"italy-13","teamId":"italy","number":13,"name":"Farid Compaore","pos":"F","height":196,"birthYear":2010,"club":"Olimpia Milano (ITA)","stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"italy-16","teamId":"italy","number":16,"name":"Andrea Chouenkam","pos":"C","height":203,"birthYear":2009,"club":"Olimpia Milano (ITA)","stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"italy-19","teamId":"italy","number":19,"name":"Nicolo Ronci","pos":"G","height":194,"birthYear":2009,"club":"Basket Santarcangelo SSDRL (ITA)","stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"italy-22","teamId":"italy","number":22,"name":"Lorenzo Zotti Pavlovic","pos":"G","height":188,"birthYear":2009,"club":"Acqua S.Bernardo Cantu (ITA)","stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"italy-44","teamId":"italy","number":44,"name":"Federico Bagordo","pos":"C","height":203,"birthYear":2009,"club":"Acqua S.Bernardo Cantu (ITA)","stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"italy-68","teamId":"italy","number":68,"name":"Mario Machetti","pos":"G","height":185,"birthYear":2009,"club":"Aquila Basket Trento (ITA)","stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"usa-4","teamId":"usa","number":4,"name":"NaVorro Bowman Jr","pos":"G","height":190,"birthYear":2009,"club":"Notre Dame H.S. (USA)","stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"usa-5","teamId":"usa","number":5,"name":"Asa Montgomery","pos":"F","height":198,"birthYear":2009,"club":"Hillgrove HS (USA)","stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"usa-6","teamId":"usa","number":6,"name":"Cayden Daughtry","pos":"G","height":178,"birthYear":2009,"club":"Calvary Christian (USA)","stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"usa-7","teamId":"usa","number":7,"name":"Mason Collins","pos":"F","height":198,"birthYear":2009,"club":"Irmo HighSchool (USA)","stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"usa-8","teamId":"usa","number":8,"name":"Jordan Page","pos":"G","height":196,"birthYear":2009,"club":"Broughton Magnet High School (USA)","stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"usa-9","teamId":"usa","number":9,"name":"Anthony Williams","pos":"F","height":203,"birthYear":2009,"club":"Eagles Landing High School (USA)","stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"usa-10","teamId":"usa","number":10,"name":"Xavier Young","pos":"C","height":205,"birthYear":2010,"club":"Faith Family Academy (USA)","stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"usa-11","teamId":"usa","number":11,"name":"JJ Crawford","pos":"G","height":193,"birthYear":2010,"club":"Rainier Beach HS (USA)","stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"usa-12","teamId":"usa","number":12,"name":"Beckham Black","pos":"G","height":188,"birthYear":2009,"club":"Southeastern Prep Academy (USA)","stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"usa-13","teamId":"usa","number":13,"name":"Joaquim Boumtje Boumtje","pos":"F","height":211,"birthYear":2009,"club":"FC Barcelona (ESP)","stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"usa-14","teamId":"usa","number":14,"name":"Clarence Rosser Jr","pos":"F","height":206,"birthYear":2009,"club":"Northern Nash High School (USA)","stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"usa-15","teamId":"usa","number":15,"name":"Erick Dampier Jr","pos":"C","height":208,"birthYear":2009,"club":"Madison-Ridgeland High School (USA)","stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"france-1","teamId":"france","number":1,"name":"Sohan Boungo","pos":"G","height":190,"birthYear":2009,"club":"BCM Gravelines Dunkerque (FRA)","stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"france-2","teamId":"france","number":2,"name":"Amadou Fall","pos":"G","height":193,"birthYear":2009,"club":"Cholet Basket (FRA)","stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"france-3","teamId":"france","number":3,"name":"Melvyn Vounang","pos":"C","height":201,"birthYear":2009,"club":"Paris Basketball (FRA)","stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"france-6","teamId":"france","number":6,"name":"Sven Ngom","pos":"C","height":214,"birthYear":2009,"club":"Pôle France (FRA)","stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"france-7","teamId":"france","number":7,"name":"Lorenz Sanz","pos":"G","height":187,"birthYear":2009,"club":"JDA Dijon Basket (FRA)","stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"france-10","teamId":"france","number":10,"name":"Dan Boudine","pos":"G","height":198,"birthYear":2009,"club":"Orleans Loiret Basket (FRA)","stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"france-14","teamId":"france","number":14,"name":"Nathan Soliman","pos":"F","height":204,"birthYear":2009,"club":"Nantes Basket Hermine (FRA)","stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"france-24","teamId":"france","number":24,"name":"Messi Yangala","pos":"F","height":203,"birthYear":2009,"club":"Pôle France (FRA)","stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"france-31","teamId":"france","number":31,"name":"Brandon Muela","pos":"F","height":203,"birthYear":2009,"club":"Pôle France (FRA)","stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"france-60","teamId":"france","number":60,"name":"Devon Agot Fortes Vieira","pos":"G","height":187,"birthYear":2009,"club":"SQBB- JSC (FRA)","stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"france-79","teamId":"france","number":79,"name":"Aaron Towo-Nansi","pos":"G","height":178,"birthYear":2009,"club":"Cholet Basket (FRA)","stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"france-93","teamId":"france","number":93,"name":"Yohan Bassoumba","pos":"F","height":200,"birthYear":2009,"club":"Caen Basket Calvados (FRA)","stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"japan-4","teamId":"japan","number":4,"name":"Eishin Konno","pos":"F","height":191,"birthYear":2009,"club":"Meisei High School (JPN)","stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"japan-5","teamId":"japan","number":5,"name":"Jurai Yamamoto","pos":"C","height":199,"birthYear":2009,"club":"Fukuoka Ohori High School (JPN)","stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"japan-6","teamId":"japan","number":6,"name":"Hiroto Kuga","pos":"G","height":186,"birthYear":2009,"club":"Fukuoka Daiichi High School (JPN)","stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"japan-7","teamId":"japan","number":7,"name":"Tetta Sakurai","pos":"G","height":180,"birthYear":2009,"club":"Ohori Senior High School (JPN)","stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"japan-8","teamId":"japan","number":8,"name":"Keiji Koshi","pos":"G","height":163,"birthYear":2009,"club":"Concordia Lutheran School (USA)","stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"japan-9","teamId":"japan","number":9,"name":"Kuon Sato","pos":"G","height":180,"birthYear":2009,"club":"Higashiyama High School (JPN)","stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"japan-10","teamId":"japan","number":10,"name":"Shunsuke Miyazato","pos":"G","height":179,"birthYear":2009,"club":"Ryukyu Golden Kings U18 (JPN)","stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"japan-11","teamId":"japan","number":11,"name":"Goodluckchinedu Ihetu","pos":"F","height":195,"birthYear":2010,"club":"Kaishi Kokusai High School (JPN)","stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"japan-13","teamId":"japan","number":13,"name":"Fumiya Kurimoto","pos":"F","height":188,"birthYear":2009,"club":"Ohori Senior High School (JPN)","stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"japan-15","teamId":"japan","number":15,"name":"Chusonjakku Shiratani","pos":"F","height":194,"birthYear":2009,"club":"Ohori Senior High School (JPN)","stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"japan-16","teamId":"japan","number":16,"name":"Herojabez Kato","pos":"F","height":189,"birthYear":2009,"club":"Chubu University Daiichi High School (JPN)","stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"japan-17","teamId":"japan","number":17,"name":"Rikuto Isoda","pos":"F","height":197,"birthYear":2010,"club":"Yokohama B-Corsairs U18 (JPN)","stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"cameroon-0","teamId":"cameroon","number":0,"name":"Edwin Mbakop Djia","pos":"G","height":178,"birthYear":2011,"club":"SLUC Nancy Basket (FRA)","stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"cameroon-1","teamId":"cameroon","number":1,"name":"Liam Levit Ngameni Fopissie","pos":"G","height":185,"birthYear":2009,"club":"Kainos Basketball Academy (CAN)","stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"cameroon-2","teamId":"cameroon","number":2,"name":"Marvyn Bidjel","pos":"G","height":190,"birthYear":2010,"club":"Vikings Basketball Academy (CMR)","stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"cameroon-4","teamId":"cameroon","number":4,"name":"Lenny Nouhet-Epesse Titi","pos":"G","height":180,"birthYear":2009,"club":"JSA Bordeaux (FRA)","stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"cameroon-6","teamId":"cameroon","number":6,"name":"Nolan Ngangmeni","pos":"G","height":188,"birthYear":2009,"club":"Saint-Charles Charenton Saint-Maurice Basket-ball (FRA)","stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"cameroon-7","teamId":"cameroon","number":7,"name":"Felix Deumi","pos":"G","height":190,"birthYear":2009,"club":"Marie Claire Noah Academy (CMR)","stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"cameroon-8","teamId":"cameroon","number":8,"name":"Mateo N'Koumngock","pos":"F","height":198,"birthYear":2009,"club":"Royal Crown Academic School (CAN)","stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"cameroon-11","teamId":"cameroon","number":11,"name":"Jason Essoua","pos":"F","height":200,"birthYear":2010,"club":"Boulazac Basket Dordogne (FRA)","stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"cameroon-12","teamId":"cameroon","number":12,"name":"Yuma Mendoua Ze","pos":"F","height":197,"birthYear":2009,"club":"Basket Club Liévinois (FRA)","stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"cameroon-22","teamId":"cameroon","number":22,"name":"Joshua Kamga Tonkam","pos":"G","height":195,"birthYear":2009,"club":"Boulogne-Levallois Metropolitans (FRA)","stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"cameroon-23","teamId":"cameroon","number":23,"name":"Lenny Djoumna","pos":"G","height":192,"birthYear":2009,"club":"Nanterre 92 (FRA)","stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"cameroon-34","teamId":"cameroon","number":34,"name":"Brice Pounouko","pos":"C","height":200,"birthYear":2010,"club":"Unibasket SSDARL (ITA)","stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"canada-0","teamId":"canada","number":0,"name":"Isaiah Clarke","pos":"F","height":198,"birthYear":2009,"club":"Triple Balance (CAN)","stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"canada-1","teamId":"canada","number":1,"name":"Kenyon St. Louis","pos":"G","height":188,"birthYear":2009,"club":"Canada Elite (CAN)","stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"canada-2","teamId":"canada","number":2,"name":"Isaiah Hamilton","pos":"F","height":198,"birthYear":2009,"club":"Crestwood Preparatory College (CAN)","stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"canada-3","teamId":"canada","number":3,"name":"Jordan Fisher","pos":"F","height":196,"birthYear":2009,"club":"Dream City Christian School (USA)","stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"canada-4","teamId":"canada","number":4,"name":"Kingston Thomas","pos":"G","height":197,"birthYear":2009,"club":"La Lumiere School (USA)","stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"canada-5","teamId":"canada","number":5,"name":"Praise Badejo","pos":"G","height":185,"birthYear":2010,"club":"King Heights Academy (CAN)","stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"canada-11","teamId":"canada","number":11,"name":"Grady Kapuanya","pos":"F","height":200,"birthYear":2009,"club":"Fort Erie International Academy (CAN)","stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"canada-12","teamId":"canada","number":12,"name":"Liam Mitakaro","pos":"G","height":188,"birthYear":2009,"club":"Iowa United (USA)","stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"canada-15","teamId":"canada","number":15,"name":"Noah D'Acre","pos":"G","height":193,"birthYear":2009,"club":"Orangeville Prep (CAN)","stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"canada-23","teamId":"canada","number":23,"name":"Tristan Edwards","pos":"F","height":200,"birthYear":2009,"club":"IMG Academy (USA)","stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"canada-34","teamId":"canada","number":34,"name":"Jeremy Gohier","pos":"C","height":229,"birthYear":2010,"club":"Nobel Elite (CAN)","stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"canada-50","teamId":"canada","number":50,"name":"Kurtis Baumann","pos":"F","height":208,"birthYear":2009,"club":"Orangeville Prep (CAN)","stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"lithuania-0","teamId":"lithuania","number":0,"name":"Kristupas Sabeckas","pos":"G","height":186,"birthYear":2009,"club":"\"Žalgiris\" Academy (LTU)","stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"lithuania-1","teamId":"lithuania","number":1,"name":"Arnas Erlickis","pos":"C","height":202,"birthYear":2009,"club":"Klaipédos KM (LTU)","stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"lithuania-2","teamId":"lithuania","number":2,"name":"Joris Sinica","pos":"F","height":198,"birthYear":2009,"club":"\"Žalgiris\" Academy (LTU)","stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"lithuania-5","teamId":"lithuania","number":5,"name":"Vytis Sliogeris","pos":"F","height":180,"birthYear":2009,"club":"Kauno krepšinio mokykla \"Perkūnas\" (LTU)","stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"lithuania-7","teamId":"lithuania","number":7,"name":"Paulius Veliulis","pos":"F","height":198,"birthYear":2009,"club":"Vsi Siauliu Krepsinio Akademijia Saule (LTU)","stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"lithuania-11","teamId":"lithuania","number":11,"name":"Benas Birzinis","pos":"F","height":200,"birthYear":2009,"club":"Sostinės krepšinio mokykla (LTU)","stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"lithuania-12","teamId":"lithuania","number":12,"name":"Jokubas Kukta","pos":"F","height":193,"birthYear":2009,"club":"\"Žalgiris\" Academy (LTU)","stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"lithuania-13","teamId":"lithuania","number":13,"name":"Rojus Stankevicius","pos":"F","height":193,"birthYear":2009,"club":"Vsi Siauliu Krepsinio Akademijia Saule (LTU)","stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"lithuania-14","teamId":"lithuania","number":14,"name":"Simas Rascius","pos":"F","height":199,"birthYear":2009,"club":"Sostinės krepšinio mokykla (LTU)","stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"lithuania-21","teamId":"lithuania","number":21,"name":"Lukas Siskauskas","pos":"G","height":181,"birthYear":2009,"club":"St. Joseph High School (USA)","stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"lithuania-35","teamId":"lithuania","number":35,"name":"Gabrielius Buivydas","pos":"G","height":195,"birthYear":2009,"club":"Vilniaus miesto krepšinio mokykla (LTU)","stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"lithuania-99","teamId":"lithuania","number":99,"name":"Augustas Kicas","pos":"G","height":178,"birthYear":2009,"club":"Nacionalinė krepšinio akademija (LTU)","stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"china-5","teamId":"china","number":5,"name":"Minghao Shi","pos":"G","height":185,"birthYear":2009,"club":"ZHEJIANG CHOUZHOU CLUB (CHN)","stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"china-6","teamId":"china","number":6,"name":"Yuxiu Chen","pos":"G","height":185,"birthYear":2009,"club":"Zhejiang Guangsha Basketball Club (CHN)","stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"china-8","teamId":"china","number":8,"name":"Yuchen Zhang","pos":"G","height":186,"birthYear":2010,"club":"The High School Attached to Tsinghua University (CHN)","stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"china-9","teamId":"china","number":9,"name":"Hanzhi Tu","pos":"F","height":191,"birthYear":2009,"club":"Sichuan Mianyang Nanshan High School (CHN)","stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"china-11","teamId":"china","number":11,"name":"Chunzhi Zhang","pos":"F","height":194,"birthYear":2009,"club":"Fujian Xunxing Basketball Club (CHN)","stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"china-12","teamId":"china","number":12,"name":"Feiyan Lyu","pos":"G","height":198,"birthYear":2010,"club":"The High School Attached to Tsinghua University (CHN)","stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"china-13","teamId":"china","number":13,"name":"Yizhaojie Zhang","pos":"F","height":203,"birthYear":2010,"club":"SHANGHAI JIUSHI CLUB (CHN)","stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"china-14","teamId":"china","number":14,"name":"Ziyi Zhang","pos":"C","height":208,"birthYear":2010,"club":"SHANGHAI JIUSHI CLUB (CHN)","stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"china-15","teamId":"china","number":15,"name":"Boxin Zhao","pos":"C","height":215,"birthYear":2010,"club":"The High School Attached to Tsinghua University (CHN)","stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"china-16","teamId":"china","number":16,"name":"Xuanyu Liu","pos":"F","height":200,"birthYear":2010,"club":"Guangdong Experimental High School (CHN)","stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"china-17","teamId":"china","number":17,"name":"Fangyu Xie","pos":"F","height":205,"birthYear":2010,"club":"Zhangqiu No. 4 High School (CHN)","stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"china-18","teamId":"china","number":18,"name":"Jiaze Yao","pos":"C","height":210,"birthYear":2010,"club":"GUANGDONG HONGYUAN CLUB (CHN)","stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"new-zealand-0","teamId":"new-zealand","number":0,"name":"Jayden Cecil","pos":"G","height":195,"birthYear":2009,"club":"Utah Prep (USA)","stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"new-zealand-1","teamId":"new-zealand","number":1,"name":"Lawson Pryor","pos":"G","height":191,"birthYear":2009,"club":"Basketball Auckland (NZL)","stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"new-zealand-3","teamId":"new-zealand","number":3,"name":"Liam Keogh","pos":"F","height":201,"birthYear":2009,"club":"Victoria State (AUS)","stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"new-zealand-4","teamId":"new-zealand","number":4,"name":"Noah Duncan","pos":"F","height":203,"birthYear":2009,"club":"Auckland Tuatara (NZL)","stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"new-zealand-5","teamId":"new-zealand","number":5,"name":"Jackson Couper","pos":"G","height":188,"birthYear":2009,"club":"Waitakere West Auckland Basketball (NZL)","stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"new-zealand-7","teamId":"new-zealand","number":7,"name":"Tawhiri Cate","pos":"G","height":191,"birthYear":2009,"club":"Canterbury Rams (NZL)","stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"new-zealand-8","teamId":"new-zealand","number":8,"name":"Zach Rampton","pos":"C","height":213,"birthYear":2009,"club":"Nelson Giants (NZL)","stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"new-zealand-9","teamId":"new-zealand","number":9,"name":"Daley Pohio","pos":"G","height":195,"birthYear":2009,"club":"Auckland Tuatara (NZL)","stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"new-zealand-11","teamId":"new-zealand","number":11,"name":"William Patten","pos":"C","height":210,"birthYear":2009,"club":"Canterbury Rams (NZL)","stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"new-zealand-12","teamId":"new-zealand","number":12,"name":"Marco Sula","pos":"F","height":203,"birthYear":2009,"club":"Canterbury Rams (NZL)","stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"new-zealand-20","teamId":"new-zealand","number":20,"name":"Malakai Tuimalealiifano","pos":"F","height":200,"birthYear":2010,"club":"Rotorua Basketball Association (NZL)","stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"new-zealand-35","teamId":"new-zealand","number":35,"name":"Matayas Thomson","pos":"G","height":183,"birthYear":2009,"club":"Auckland Basketball (NZL)","stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"slovenia-4","teamId":"slovenia","number":4,"name":"Hugo Rene Godec","pos":"F","height":195,"birthYear":2009,"club":"KK Jance (SLO)","stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"slovenia-5","teamId":"slovenia","number":5,"name":"Aleks Pejic Rupnik","pos":"G","height":195,"birthYear":2009,"club":"Gorica (SLO)","stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"slovenia-6","teamId":"slovenia","number":6,"name":"Nejc Slapnik","pos":"G","height":190,"birthYear":2009,"club":"ECE Triglav (SLO)","stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"slovenia-7","teamId":"slovenia","number":7,"name":"Jakob Siftar","pos":"G","height":198,"birthYear":2009,"club":"FC Barcelona (ESP)","stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"slovenia-8","teamId":"slovenia","number":8,"name":"Maj Tomsic Vujkovic","pos":"G","height":190,"birthYear":2010,"club":"KK Ilirija (SLO)","stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"slovenia-9","teamId":"slovenia","number":9,"name":"Nejc Pirnat","pos":"F","height":197,"birthYear":2009,"club":"KK Grosuplje (SLO)","stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"slovenia-10","teamId":"slovenia","number":10,"name":"Maks Anderlic","pos":"G","height":194,"birthYear":2009,"club":"KK Ilirija (SLO)","stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"slovenia-11","teamId":"slovenia","number":11,"name":"Jaka Jovanovic","pos":"F","height":200,"birthYear":2009,"club":"Zlatorog Lasko (SLO)","stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"slovenia-12","teamId":"slovenia","number":12,"name":"Matic Rezec","pos":"G","height":196,"birthYear":2009,"club":"Zlatorog Lasko (SLO)","stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"slovenia-13","teamId":"slovenia","number":13,"name":"Lun Jarc","pos":"F","height":207,"birthYear":2009,"club":"Mega MIS (SRB)","stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"slovenia-14","teamId":"slovenia","number":14,"name":"Rok Ilic","pos":"C","height":199,"birthYear":2009,"club":"Cedevita Olimpija (SLO)","stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"slovenia-15","teamId":"slovenia","number":15,"name":"Nejc Roznik","pos":"C","height":204,"birthYear":2009,"club":"Cedevita Olimpija (SLO)","stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"puerto-rico-0","teamId":"puerto-rico","number":0,"name":"Jodereck Torres","pos":"F","height":185,"birthYear":2009,"club":"MIAMI CHRISTIAN ACADEMY (USA)","stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"puerto-rico-1","teamId":"puerto-rico","number":1,"name":"Jeremy Willmore","pos":"G","height":183,"birthYear":2009,"club":"Balboa Academy (USA)","stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"puerto-rico-2","teamId":"puerto-rico","number":2,"name":"Dwight Gaines","pos":"G","height":178,"birthYear":2009,"club":"Westminster Academy (USA)","stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"puerto-rico-3","teamId":"puerto-rico","number":3,"name":"Jomar Alejandro Rodriguez Rivera","pos":"G","height":191,"birthYear":2009,"club":"COLEGIO SAN ANTONIO (PUR)","stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"puerto-rico-5","teamId":"puerto-rico","number":5,"name":"Eduyn Albino","pos":"G","height":188,"birthYear":2009,"club":"MASIS SCHOOL (PUR)","stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"puerto-rico-10","teamId":"puerto-rico","number":10,"name":"Ivaniel Lopez Arache","pos":"F","height":198,"birthYear":2010,"club":"ACADEMIA PRESBITERIANA (PUR)","stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"puerto-rico-11","teamId":"puerto-rico","number":11,"name":"John Arroyo","pos":"G","height":191,"birthYear":2009,"club":"The Academy of Central Florida (USA)","stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"puerto-rico-12","teamId":"puerto-rico","number":12,"name":"Alexis Fuentes","pos":"F","height":196,"birthYear":2009,"club":"BCAT (USA)","stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"puerto-rico-13","teamId":"puerto-rico","number":13,"name":"Yaddiel Sanchez","pos":"C","height":196,"birthYear":2009,"club":"The Academy of Central Florida (USA)","stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"puerto-rico-15","teamId":"puerto-rico","number":15,"name":"Michael Portilla","pos":"G","height":180,"birthYear":2009,"club":"GUAMANI PRIVATE SCHOOL (PUR)","stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"puerto-rico-20","teamId":"puerto-rico","number":20,"name":"Darell Rodriguez","pos":"C","height":198,"birthYear":2009,"club":"Academia Cristo Rey (PUR)","stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"puerto-rico-21","teamId":"puerto-rico","number":21,"name":"Luis Rosado","pos":"F","height":196,"birthYear":2009,"club":"ROBBINSVILLE HIGH SCHOOL (USA)","stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"turkiye-1","teamId":"turkiye","number":1,"name":"Demir Ozturk","pos":"F","height":202,"birthYear":2009,"club":"Anadolu Efes SK (TUR)","stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"turkiye-2","teamId":"turkiye","number":2,"name":"Darius Karutasu","pos":"G","height":201,"birthYear":2009,"club":"Anadolu Efes SK (TUR)","stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"turkiye-4","teamId":"turkiye","number":4,"name":"Ruzgar Opcun","pos":"C","height":211,"birthYear":2009,"club":"Fenerbahçe Beko (TUR)","stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"turkiye-5","teamId":"turkiye","number":5,"name":"Besir Briant","pos":"F","height":205,"birthYear":2009,"club":"Karsiyaka (TUR)","stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"turkiye-8","teamId":"turkiye","number":8,"name":"Arda Ozturk","pos":"F","height":204,"birthYear":2010,"club":"Anadolu Efes SK (TUR)","stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"turkiye-10","teamId":"turkiye","number":10,"name":"Omer Kutluay","pos":"G","height":193,"birthYear":2009,"club":"Real Madrid (ESP)","stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"turkiye-11","teamId":"turkiye","number":11,"name":"Kartal Bora Simsek","pos":"G","height":195,"birthYear":2009,"club":"Bahcesehir Koleji (TUR)","stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"turkiye-13","teamId":"turkiye","number":13,"name":"Omer Yusuf Sik","pos":"G","height":190,"birthYear":2009,"club":"Fenerbahçe Beko (TUR)","stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"turkiye-16","teamId":"turkiye","number":16,"name":"Atahan Agacdelen","pos":"F","height":202,"birthYear":2009,"club":"Aliaga Petkimspor (TUR)","stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"turkiye-17","teamId":"turkiye","number":17,"name":"Noyan Tolan","pos":"F","height":200,"birthYear":2009,"club":"Valencia Basket Club SAD (ESP)","stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"turkiye-24","teamId":"turkiye","number":24,"name":"Sarp Kaya Arda","pos":"G","height":182,"birthYear":2009,"club":"University of Vermont (USA)","stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"turkiye-41","teamId":"turkiye","number":41,"name":"Emre Yazici","pos":"F","height":197,"birthYear":2009,"club":"Aliaga Petkimspor (TUR)","stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"venezuela-0","teamId":"venezuela","number":0,"name":"Cristhian Jose Perez Rivas","pos":"G","height":185,"birthYear":2009,"club":"club santa rosa (VEN)","stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"venezuela-3","teamId":"venezuela","number":3,"name":"Julio Vasquez","pos":"G","height":190,"birthYear":2009,"club":"Dreamland Gran Canaria (ESP)","stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"venezuela-5","teamId":"venezuela","number":5,"name":"Bryan Gomez","pos":"G","height":192,"birthYear":2009,"club":"Angeles de Cocuima (VEN)","stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"venezuela-7","teamId":"venezuela","number":7,"name":"Kevin Gutierrez","pos":"F","height":196,"birthYear":2009,"club":"ASD Stella Azzurra Brindisi (ITA)","stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"venezuela-8","teamId":"venezuela","number":8,"name":"Williams Anillo","pos":"G","height":180,"birthYear":2009,"club":"rider de baruta (VEN)","stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"venezuela-9","teamId":"venezuela","number":9,"name":"Ezequiel Perez","pos":"F","height":191,"birthYear":2009,"club":"La Laguna Tenerife (ESP)","stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"venezuela-11","teamId":"venezuela","number":11,"name":"Carlos Perez","pos":"G","height":183,"birthYear":2009,"club":"Cocodrilos de Caracas (VEN)","stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"venezuela-12","teamId":"venezuela","number":12,"name":"Ricardo Villarroel","pos":"F","height":196,"birthYear":2009,"club":"escuela jose arias eba (VEN)","stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"venezuela-15","teamId":"venezuela","number":15,"name":"Chris Manuel Echezuria Duran","pos":"G","height":188,"birthYear":2011,"club":"Pablo Laso Academy (ESP)","stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"venezuela-30","teamId":"venezuela","number":30,"name":"Santiago Gines","pos":"F","height":191,"birthYear":2009,"club":"trapichito de guarenas (VEN)","stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"venezuela-34","teamId":"venezuela","number":34,"name":"Samuel Uzcategui","pos":"F","height":189,"birthYear":2009,"club":"Norwood Flames (AUS)","stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"venezuela-47","teamId":"venezuela","number":47,"name":"Enzo Nash Sgherza","pos":"C","height":198,"birthYear":2009,"club":"Trotamundos (VEN)","stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"australia-4","teamId":"australia","number":4,"name":"Andrew Watene","pos":"G","height":185,"birthYear":2009,"club":"Queensland State (AUS)","stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"australia-5","teamId":"australia","number":5,"name":"Tom Dammers","pos":"G","height":187,"birthYear":2009,"club":"Victoria State (AUS)","stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"australia-6","teamId":"australia","number":6,"name":"Josh McCann","pos":"F","height":196,"birthYear":2009,"club":"Victoria State (AUS)","stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"australia-7","teamId":"australia","number":7,"name":"Luke Paul","pos":"G","height":198,"birthYear":2009,"club":"Cairns Taipans (AUS)","stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"australia-9","teamId":"australia","number":9,"name":"Antonio Browne","pos":"F","height":193,"birthYear":2009,"club":"Centre of Excellence (AUS)","stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"australia-10","teamId":"australia","number":10,"name":"Lucas Byrne","pos":"F","height":192,"birthYear":2009,"club":"Victoria State (AUS)","stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"australia-11","teamId":"australia","number":11,"name":"William Hamilton","pos":"F","height":196,"birthYear":2009,"club":"Centre of Excellence (AUS)","stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"australia-12","teamId":"australia","number":12,"name":"John Aryang","pos":"F","height":198,"birthYear":2009,"club":"Western Australia (AUS)","stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"australia-13","teamId":"australia","number":13,"name":"Riak Akhuar","pos":"F","height":200,"birthYear":2009,"club":"Victoria State (AUS)","stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"australia-14","teamId":"australia","number":14,"name":"Yahya Basaran","pos":"C","height":214,"birthYear":2009,"club":"Centre of Excellence (AUS)","stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"australia-15","teamId":"australia","number":15,"name":"Alex Mabbott","pos":"C","height":211,"birthYear":2009,"club":"Spire Academy (USA)","stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"australia-31","teamId":"australia","number":31,"name":"Alex Edwards","pos":"F","height":198,"birthYear":2009,"club":"Western Australia (AUS)","stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"serbia-2","teamId":"serbia","number":2,"name":"Luka Galic","pos":"F","height":199,"birthYear":2009,"club":"Igokea m:tel (BIH)","stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"serbia-3","teamId":"serbia","number":3,"name":"Nikola Durovic","pos":"F","height":210,"birthYear":2009,"club":"Partizan NIS (SRB)","stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"serbia-7","teamId":"serbia","number":7,"name":"Vuk Stepanovic","pos":"G","height":191,"birthYear":2009,"club":"KK Mega Basket (SRB)","stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"serbia-9","teamId":"serbia","number":9,"name":"Ognjen Simjanovski","pos":"G","height":191,"birthYear":2009,"club":"Crvena Zvezda MTS (SRB)","stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"serbia-10","teamId":"serbia","number":10,"name":"Marko Veselinovic","pos":"F","height":200,"birthYear":2009,"club":"Crvena Zvezda MTS (SRB)","stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"serbia-11","teamId":"serbia","number":11,"name":"Matija Lukic","pos":"G","height":202,"birthYear":2009,"club":"Casademont Zaragoza (ESP)","stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"serbia-12","teamId":"serbia","number":12,"name":"Vaso Saponjic","pos":"F","height":197,"birthYear":2009,"club":"BC Cacak 94 (SRB)","stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"serbia-18","teamId":"serbia","number":18,"name":"Luka Miladinovic","pos":"C","height":209,"birthYear":2009,"club":"Partizan NIS (SRB)","stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"serbia-22","teamId":"serbia","number":22,"name":"Petar Bjelica","pos":"F","height":208,"birthYear":2009,"club":"BC Mega Basket Beograd (SRB)","stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"serbia-25","teamId":"serbia","number":25,"name":"Nikola Kusturica","pos":"G","height":202,"birthYear":2009,"club":"FC Barcelona (ESP)","stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"serbia-31","teamId":"serbia","number":31,"name":"Lazar Milicic","pos":"F","height":196,"birthYear":2009,"club":"Pablo Laso Academy (ESP)","stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"serbia-95","teamId":"serbia","number":95,"name":"Luka Pavlovic","pos":"G","height":184,"birthYear":2009,"club":"Partizan NIS (SRB)","stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"cote-divoire-0","teamId":"cote-divoire","number":0,"name":"Tesilan Ferdinando Doumbouya","pos":"F","height":204,"birthYear":2009,"club":"A.D. Fortitudo basket Pozzuoli (ITA)","stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"cote-divoire-1","teamId":"cote-divoire","number":1,"name":"Kpadja Barakel Koffi","pos":"G","height":188,"birthYear":2010,"club":"Phelps High School (USA)","stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"cote-divoire-2","teamId":"cote-divoire","number":2,"name":"Ibrahim Khalil Fadiga","pos":"G","height":182,"birthYear":2010,"club":"Fryshuset Basket (SWE)","stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"cote-divoire-3","teamId":"cote-divoire","number":3,"name":"Jean-Charles Martin Kadjo Siransi","pos":"G","height":190,"birthYear":2010,"club":"Salesian (USA)","stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"cote-divoire-4","teamId":"cote-divoire","number":4,"name":"Omar Mangassouba","pos":"G","height":192,"birthYear":2009,"club":"Newark East Side (USA)","stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"cote-divoire-7","teamId":"cote-divoire","number":7,"name":"Yves Roland Jonas Nathan Djako","pos":"G","height":192,"birthYear":2010,"club":"Hypersonics Baasketball (CIV)","stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"cote-divoire-8","teamId":"cote-divoire","number":8,"name":"Antoine Mohamed Konan","pos":"G","height":193,"birthYear":2010,"club":"JTS FUSION (CIV)","stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"cote-divoire-10","teamId":"cote-divoire","number":10,"name":"Jean-Philippe Oka","pos":"F","height":203,"birthYear":2009,"club":"Brave Lions (USA)","stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"cote-divoire-12","teamId":"cote-divoire","number":12,"name":"Ladji Adama Konaté","pos":"C","height":205,"birthYear":2009,"club":"JTS FUSION (CIV)","stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"cote-divoire-22","teamId":"cote-divoire","number":22,"name":"Adama Sisi Kone","pos":"F","height":195,"birthYear":2009,"club":"Brave Lions (USA)","stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"cote-divoire-32","teamId":"cote-divoire","number":32,"name":"Irene Raphael Ouedraogo","pos":"C","height":209,"birthYear":2010,"club":"Wilson Academy (USA)","stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"cote-divoire-78","teamId":"cote-divoire","number":78,"name":"Joris Komenan Pierre Kouadio","pos":"G","height":187,"birthYear":2009,"club":"Wilson Academy (USA)","stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]}
  ]
};
