/* ============================================================================
   HoopScout — data file  (window.HOOPDATA)
   ----------------------------------------------------------------------------
   Rosters: official confirmed player lists for the FIBA U17 World Cup 2026,
   announced 26 Jun 2026. Teams marked rosterType:"pool" list the full
   training-camp pool (more than 12) — the final 12 that dress for a given game
   may be a subset. Teams with exactly 12 are marked "final12".

   What's filled: team, group, player names.
   What's NOT yet filled: jersey number, position, height, birth year, stats —
   these aren't in the public roster text. Add them with scraper.js on each FIBA
   team page (numbers/positions) and game page (stats). See README.
   Schema for a player object is documented in README / earlier version.
   ========================================================================== */

window.HOOPDATA = {
  event: {
    name: "FIBA U17 Basketball World Cup 2026",
    short: "U17 World Cup 2026",
    id: 208545,
    city: "Istanbul, Türkiye",
    dates: "27 Jun – 5 Jul 2026",
    url: "https://www.fiba.basketball/en/events/fiba-u17-basketball-world-cup-2026"
  },
  groups: {
    A: ["italy","usa","france","japan"],
    B: ["cameroon","canada","lithuania","china"],
    C: ["new-zealand","slovenia","puerto-rico","turkiye"],
    D: ["venezuela","australia","serbia","cote-divoire"]
  },
  teams: [
    {
      "id": "italy",
      "name": "Italy",
      "code": "ITA",
      "group": "A",
      "rosterType": "pool",
      "count": 18,
      "rosterUrl": "https://www.fiba.basketball/en/events/fiba-u17-basketball-world-cup-2026/teams/italy#roster"
    },
    {
      "id": "usa",
      "name": "USA",
      "code": "USA",
      "group": "A",
      "rosterType": "final12",
      "count": 12,
      "rosterUrl": "https://www.fiba.basketball/en/events/fiba-u17-basketball-world-cup-2026/teams/usa#roster"
    },
    {
      "id": "france",
      "name": "France",
      "code": "FRA",
      "group": "A",
      "rosterType": "pool",
      "count": 18,
      "rosterUrl": "https://www.fiba.basketball/en/events/fiba-u17-basketball-world-cup-2026/teams/france#roster"
    },
    {
      "id": "japan",
      "name": "Japan",
      "code": "JPN",
      "group": "A",
      "rosterType": "final12",
      "count": 12,
      "rosterUrl": "https://www.fiba.basketball/en/events/fiba-u17-basketball-world-cup-2026/teams/japan#roster"
    },
    {
      "id": "cameroon",
      "name": "Cameroon",
      "code": "CMR",
      "group": "B",
      "rosterType": "pool",
      "count": 15,
      "rosterUrl": "https://www.fiba.basketball/en/events/fiba-u17-basketball-world-cup-2026/teams/cameroon#roster"
    },
    {
      "id": "canada",
      "name": "Canada",
      "code": "CAN",
      "group": "B",
      "rosterType": "final12",
      "count": 12,
      "rosterUrl": "https://www.fiba.basketball/en/events/fiba-u17-basketball-world-cup-2026/teams/canada#roster"
    },
    {
      "id": "lithuania",
      "name": "Lithuania",
      "code": "LTU",
      "group": "B",
      "rosterType": "final12",
      "count": 12,
      "rosterUrl": "https://www.fiba.basketball/en/events/fiba-u17-basketball-world-cup-2026/teams/lithuania#roster"
    },
    {
      "id": "china",
      "name": "China",
      "code": "CHN",
      "group": "B",
      "rosterType": "pool",
      "count": 20,
      "rosterUrl": "https://www.fiba.basketball/en/events/fiba-u17-basketball-world-cup-2026/teams/china#roster"
    },
    {
      "id": "new-zealand",
      "name": "New Zealand",
      "code": "NZL",
      "group": "C",
      "rosterType": "final12",
      "count": 12,
      "rosterUrl": "https://www.fiba.basketball/en/events/fiba-u17-basketball-world-cup-2026/teams/new-zealand#roster"
    },
    {
      "id": "slovenia",
      "name": "Slovenia",
      "code": "SLO",
      "group": "C",
      "rosterType": "pool",
      "count": 19,
      "rosterUrl": "https://www.fiba.basketball/en/events/fiba-u17-basketball-world-cup-2026/teams/slovenia#roster"
    },
    {
      "id": "puerto-rico",
      "name": "Puerto Rico",
      "code": "PUR",
      "group": "C",
      "rosterType": "final12",
      "count": 12,
      "rosterUrl": "https://www.fiba.basketball/en/events/fiba-u17-basketball-world-cup-2026/teams/puerto-rico#roster"
    },
    {
      "id": "turkiye",
      "name": "Türkiye",
      "code": "TUR",
      "group": "C",
      "rosterType": "pool",
      "count": 19,
      "rosterUrl": "https://www.fiba.basketball/en/events/fiba-u17-basketball-world-cup-2026/teams/turkiye#roster"
    },
    {
      "id": "venezuela",
      "name": "Venezuela",
      "code": "VEN",
      "group": "D",
      "rosterType": "pool",
      "count": 26,
      "rosterUrl": "https://www.fiba.basketball/en/events/fiba-u17-basketball-world-cup-2026/teams/venezuela#roster"
    },
    {
      "id": "australia",
      "name": "Australia",
      "code": "AUS",
      "group": "D",
      "rosterType": "final12",
      "count": 12,
      "rosterUrl": "https://www.fiba.basketball/en/events/fiba-u17-basketball-world-cup-2026/teams/australia#roster"
    },
    {
      "id": "serbia",
      "name": "Serbia",
      "code": "SRB",
      "group": "D",
      "rosterType": "pool",
      "count": 22,
      "rosterUrl": "https://www.fiba.basketball/en/events/fiba-u17-basketball-world-cup-2026/teams/serbia#roster"
    },
    {
      "id": "cote-divoire",
      "name": "Côte d'Ivoire",
      "code": "CIV",
      "group": "D",
      "rosterType": "pool",
      "count": 20,
      "rosterUrl": "https://www.fiba.basketball/en/events/fiba-u17-basketball-world-cup-2026/teams/cote-divoire#roster"
    }
  ],
  players: [
    {"id":"australia-riak-akhuar","teamId":"australia","number":null,"name":"Riak Akhuar","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"australia-john-aryang","teamId":"australia","number":null,"name":"John Aryang","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"australia-ahmet-yahya-basaran","teamId":"australia","number":null,"name":"Ahmet Yahya Basaran","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"australia-antonio-browne","teamId":"australia","number":null,"name":"Antonio Browne","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"australia-lucas-byrne","teamId":"australia","number":null,"name":"Lucas Byrne","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"australia-tom-dammers","teamId":"australia","number":null,"name":"Tom Dammers","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"australia-william-hamilton","teamId":"australia","number":null,"name":"William Hamilton","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"australia-isaiah-jorgenson","teamId":"australia","number":null,"name":"Isaiah Jorgenson","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"australia-alexander-mabbott","teamId":"australia","number":null,"name":"Alexander Mabbott","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"australia-josh-mccann","teamId":"australia","number":null,"name":"Josh McCann","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"australia-luke-paul","teamId":"australia","number":null,"name":"Luke Paul","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"australia-andrew-watene","teamId":"australia","number":null,"name":"Andrew Watene","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"cameroon-bayero-aliyou","teamId":"cameroon","number":null,"name":"Bayero Aliyou","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"cameroon-marvin-bidjel","teamId":"cameroon","number":null,"name":"Marvin Bidjel","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"cameroon-matthew-chatue","teamId":"cameroon","number":null,"name":"Matthew Chatue","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"cameroon-felix-deumi","teamId":"cameroon","number":null,"name":"Felix Deumi","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"cameroon-lenny-djoumna","teamId":"cameroon","number":null,"name":"Lenny Djoumna","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"cameroon-lenny-epesse","teamId":"cameroon","number":null,"name":"Lenny Epesse","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"cameroon-jason-essoua","teamId":"cameroon","number":null,"name":"Jason Essoua","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"cameroon-tobbo-eyoum","teamId":"cameroon","number":null,"name":"Tobbo Eyoum","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"cameroon-joshua-kamga","teamId":"cameroon","number":null,"name":"Joshua Kamga","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"cameroon-mateo-k-koumngock","teamId":"cameroon","number":null,"name":"Mateo K'Koumngock","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"cameroon-edwin-mbakop","teamId":"cameroon","number":null,"name":"Edwin Mbakop","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"cameroon-kemi-mendoua","teamId":"cameroon","number":null,"name":"Kemi Mendoua","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"cameroon-liam-ngameni","teamId":"cameroon","number":null,"name":"Liam Ngameni","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"cameroon-nolan-ngangmeni","teamId":"cameroon","number":null,"name":"Nolan Ngangmeni","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"cameroon-mouliom-pounouko","teamId":"cameroon","number":null,"name":"Mouliom Pounouko","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"canada-praise-badejo","teamId":"canada","number":null,"name":"Praise Badejo","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"canada-kurtis-baumann","teamId":"canada","number":null,"name":"Kurtis Baumann","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"canada-isaiah-clarke","teamId":"canada","number":null,"name":"Isaiah Clarke","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"canada-noah-d-acre","teamId":"canada","number":null,"name":"Noah D'Acre","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"canada-tristan-edwards","teamId":"canada","number":null,"name":"Tristan Edwards","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"canada-jordan-fisher","teamId":"canada","number":null,"name":"Jordan Fisher","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"canada-jeremy-gohier","teamId":"canada","number":null,"name":"Jérémy Gohier","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"canada-isaiah-hamilton","teamId":"canada","number":null,"name":"Isaiah Hamilton","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"canada-grady-kapuanya","teamId":"canada","number":null,"name":"Grady Kapuanya","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"canada-liam-mitakaro","teamId":"canada","number":null,"name":"Liam Mitakaro","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"canada-kenyon-st-louis","teamId":"canada","number":null,"name":"Kenyon St. Louis","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"canada-kingston-thomas","teamId":"canada","number":null,"name":"Kingston Thomas","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"china-yuxiu-chen","teamId":"china","number":null,"name":"Yuxiu Chen","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"china-zihong-fan","teamId":"china","number":null,"name":"Zihong Fan","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"china-siyuan-liu","teamId":"china","number":null,"name":"Siyuan Liu","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"china-xuanyu-liu","teamId":"china","number":null,"name":"Xuanyu Liu","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"china-feiyan-lyu","teamId":"china","number":null,"name":"Feiyan Lyu","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"china-pengfan-qi","teamId":"china","number":null,"name":"Pengfan Qi","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"china-minghao-shi","teamId":"china","number":null,"name":"Minghao Shi","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"china-hanzhi-tu","teamId":"china","number":null,"name":"Hanzhi Tu","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"china-fangyu-xie","teamId":"china","number":null,"name":"Fangyu Xie","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"china-zimo-yang","teamId":"china","number":null,"name":"Zimo Yang","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"china-jiaze-yao","teamId":"china","number":null,"name":"Jiaze Yao","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"china-shengbin-yao","teamId":"china","number":null,"name":"Shengbin Yao","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"china-boran-yue","teamId":"china","number":null,"name":"Boran Yue","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"china-boxin-zhao","teamId":"china","number":null,"name":"Boxin Zhao","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"china-zhanfeng-zhou","teamId":"china","number":null,"name":"Zhanfeng Zhou","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"china-chunzhi-zhang","teamId":"china","number":null,"name":"Chunzhi Zhang","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"china-junyan-zhang","teamId":"china","number":null,"name":"Junyan Zhang","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"china-yizhaojie-zhang","teamId":"china","number":null,"name":"Yizhaojie Zhang","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"china-yuchen-zhang","teamId":"china","number":null,"name":"Yuchen Zhang","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"china-ziyi-zhang","teamId":"china","number":null,"name":"Ziyi Zhang","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"cote-divoire-owo-paul-emmanuel-adja","teamId":"cote-divoire","number":null,"name":"Owo Paul Emmanuel Adja","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"cote-divoire-diomande-bilali-camara-bahie","teamId":"cote-divoire","number":null,"name":"Diomandé Bilali Camara Bahie","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"cote-divoire-yves-roland-jonas-nathan-djako","teamId":"cote-divoire","number":null,"name":"Yves Roland Jonas Nathan Djako","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"cote-divoire-ewan-khader-fils-doumbia","teamId":"cote-divoire","number":null,"name":"Ewan Khader Fils Doumbia","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"cote-divoire-tesilan-ferdinando-doumbouya","teamId":"cote-divoire","number":null,"name":"Tesilan Ferdinando Doumbouya","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"cote-divoire-atche-pierre-daniel-ezoua","teamId":"cote-divoire","number":null,"name":"Atche Pierre-Daniel Ezoua","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"cote-divoire-ibrahim-khalil-fadiga","teamId":"cote-divoire","number":null,"name":"Ibrahim Khalil Fadiga","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"cote-divoire-ismael-kahlil-issouf","teamId":"cote-divoire","number":null,"name":"Ismael Kahlil Issouf","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"cote-divoire-kpadja-barakel-koffi","teamId":"cote-divoire","number":null,"name":"Kpadja Barakel Koffi","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"cote-divoire-ladji-adama-konate","teamId":"cote-divoire","number":null,"name":"Ladji Adama Konate","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"cote-divoire-adama-sisi-kone","teamId":"cote-divoire","number":null,"name":"Adama Sisi Kone","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"cote-divoire-joris-komenan-pierre-kouadio","teamId":"cote-divoire","number":null,"name":"Joris Komenan Pierre Kouadio","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"cote-divoire-nelson-jean-baptiste-isaac-chola-logue","teamId":"cote-divoire","number":null,"name":"Nelson Jean-Baptiste Isaac Chola Logue","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"cote-divoire-omar-mangassouba","teamId":"cote-divoire","number":null,"name":"Omar Mangassouba","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"cote-divoire-gabin-ismael-namoano-quintin","teamId":"cote-divoire","number":null,"name":"Gabin Ismael Namoano-Quintin","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"cote-divoire-minty-jean-philippe-dylan-oka","teamId":"cote-divoire","number":null,"name":"Minty Jean-Philippe Dylan Oka","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"cote-divoire-emmanuel-irene-raphael-ouedraogo","teamId":"cote-divoire","number":null,"name":"Emmanuel Irené Raphael Ouedraogo","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"cote-divoire-lyven-lewis-porsan","teamId":"cote-divoire","number":null,"name":"Lyven Lewis Porsan","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"cote-divoire-jean-charles-martin-kadjo-siransi","teamId":"cote-divoire","number":null,"name":"Jean-Charles Martin Kadjo Siransi","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"cote-divoire-otys-lilian-seka-yapo","teamId":"cote-divoire","number":null,"name":"Otys Lilian Seka Yapo","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"france-yohan-bassoumba","teamId":"france","number":null,"name":"Yohan Bassoumba","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"france-dan-boudine","teamId":"france","number":null,"name":"Dan Boudine","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"france-sohan-boungo","teamId":"france","number":null,"name":"Sohan Boungo","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"france-gangaly-diallo","teamId":"france","number":null,"name":"Gangaly Diallo","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"france-amadou-fall","teamId":"france","number":null,"name":"Amadou Fall","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"france-arthur-gruszka","teamId":"france","number":null,"name":"Arthur Gruszka","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"france-tom-heidet","teamId":"france","number":null,"name":"Tom Heidet","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"france-ilan-laville-guillon","teamId":"france","number":null,"name":"Ilan Laville-Guillon","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"france-brandon-muela","teamId":"france","number":null,"name":"Brandon Muela","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"france-sven-ngom","teamId":"france","number":null,"name":"Sven Ngom","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"france-paul-nnanga","teamId":"france","number":null,"name":"Paul Nnanga","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"france-lorenz-sanz","teamId":"france","number":null,"name":"Lorenz Sanz","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"france-nathan-soliman","teamId":"france","number":null,"name":"Nathan Soliman","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"france-cesar-thenawha","teamId":"france","number":null,"name":"Cesar Thenawha","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"france-aaron-towo-nansi","teamId":"france","number":null,"name":"Aaron Towo-Nansi","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"france-melvyn-vounang","teamId":"france","number":null,"name":"Melvyn Vounang","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"france-messi-yangala","teamId":"france","number":null,"name":"Messi Yangala","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"france-riley-zizi","teamId":"france","number":null,"name":"Riley Zizi","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"italy-alessandro-alba","teamId":"italy","number":null,"name":"Alessandro Alba","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"italy-federico-bagordo","teamId":"italy","number":null,"name":"Federico Bagordo","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"italy-guglielmo-baldasseroni","teamId":"italy","number":null,"name":"Guglielmo Baldasseroni","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"italy-david-jack-bonomi","teamId":"italy","number":null,"name":"David Jack Bonomi","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"italy-andrea-chouenkam","teamId":"italy","number":null,"name":"Andrea Chouenkam","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"italy-farid-compaore","teamId":"italy","number":null,"name":"Farid Compaore","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"italy-paolo-lojacono","teamId":"italy","number":null,"name":"Paolo Lojacono","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"italy-mario-macchetti","teamId":"italy","number":null,"name":"Mario Macchetti","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"italy-cristian-malano","teamId":"italy","number":null,"name":"Cristian Malano","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"italy-marco-milazzo","teamId":"italy","number":null,"name":"Marco Milazzo","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"italy-leonardo-nicolodi","teamId":"italy","number":null,"name":"Leonardo Nicolodi","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"italy-filippo-papale","teamId":"italy","number":null,"name":"Filippo Papale","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"italy-nicolo-ronci","teamId":"italy","number":null,"name":"Nicolo Ronci","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"italy-mattia-ruggeri","teamId":"italy","number":null,"name":"Mattia Ruggeri","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"italy-lapo-santini","teamId":"italy","number":null,"name":"Lapo Santini","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"italy-simone-ventura","teamId":"italy","number":null,"name":"Simone Ventura","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"italy-jacopo-vogogna","teamId":"italy","number":null,"name":"Jacopo Vogogna","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"italy-lorenzo-zotti","teamId":"italy","number":null,"name":"Lorenzo Zotti","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"japan-goodluck-chinedu-ihetsu","teamId":"japan","number":null,"name":"Goodluck Chinedu Ihetsu","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"japan-rikuto-isoda","teamId":"japan","number":null,"name":"Rikuto Isoda","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"japan-herojabez-kato","teamId":"japan","number":null,"name":"Herojabez Kato","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"japan-eishin-konno","teamId":"japan","number":null,"name":"Eishin Konno","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"japan-keiji-koshi","teamId":"japan","number":null,"name":"Keiji Koshi","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"japan-hiroto-kuga","teamId":"japan","number":null,"name":"Hiroto Kuga","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"japan-fumiya-kurimoto","teamId":"japan","number":null,"name":"Fumiya Kurimoto","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"japan-shunsuke-miyazato","teamId":"japan","number":null,"name":"Shunsuke Miyazato","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"japan-kuon-sato","teamId":"japan","number":null,"name":"Kuon Sato","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"japan-tetta-sakurai","teamId":"japan","number":null,"name":"Tetta Sakurai","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"japan-chuson-jack-shiratani","teamId":"japan","number":null,"name":"Chuson Jack Shiratani","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"japan-jurai-yamamoto","teamId":"japan","number":null,"name":"Jurai Yamamoto","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"lithuania-benas-birzinis","teamId":"lithuania","number":null,"name":"Benas Birzinis","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"lithuania-gabrielius-buivydas","teamId":"lithuania","number":null,"name":"Gabrielius Buivydas","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"lithuania-arnas-erlickis","teamId":"lithuania","number":null,"name":"Arnas Erlickis","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"lithuania-augustas-kicas","teamId":"lithuania","number":null,"name":"Augustas Kicas","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"lithuania-jokubas-kukta","teamId":"lithuania","number":null,"name":"Jokubas Kukta","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"lithuania-simas-rascius","teamId":"lithuania","number":null,"name":"Simas Rascius","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"lithuania-kristupas-sabeckas","teamId":"lithuania","number":null,"name":"Kristupas Sabeckas","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"lithuania-joris-sinica","teamId":"lithuania","number":null,"name":"Joris Sinica","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"lithuania-lukas-siskauskas","teamId":"lithuania","number":null,"name":"Lukas Siskauskas","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"lithuania-vytis-sliogeris","teamId":"lithuania","number":null,"name":"Vytis Sliogeris","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"lithuania-rojus-stankevicius","teamId":"lithuania","number":null,"name":"Rojus Stankevicius","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"lithuania-paulius-veliulis","teamId":"lithuania","number":null,"name":"Paulius Veliulis","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"new-zealand-tawhiri-cate","teamId":"new-zealand","number":null,"name":"Tawhiri Cate","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"new-zealand-jayden-cecil","teamId":"new-zealand","number":null,"name":"Jayden Cecil","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"new-zealand-jackson-couper","teamId":"new-zealand","number":null,"name":"Jackson Couper","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"new-zealand-noah-nuncan","teamId":"new-zealand","number":null,"name":"Noah Nuncan","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"new-zealand-liam-keogh","teamId":"new-zealand","number":null,"name":"Liam Keogh","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"new-zealand-will-patten","teamId":"new-zealand","number":null,"name":"Will Patten","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"new-zealand-daley-pohio","teamId":"new-zealand","number":null,"name":"Daley Pohio","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"new-zealand-lawson-pryor","teamId":"new-zealand","number":null,"name":"Lawson Pryor","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"new-zealand-zach-rampton","teamId":"new-zealand","number":null,"name":"Zach Rampton","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"new-zealand-marco-sula","teamId":"new-zealand","number":null,"name":"Marco Sula","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"new-zealand-malakai-tuimalealiifano","teamId":"new-zealand","number":null,"name":"Malakai Tuimalealiifano","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"new-zealand-taye-thomson","teamId":"new-zealand","number":null,"name":"Taye Thomson","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"puerto-rico-eduyn-albino","teamId":"puerto-rico","number":null,"name":"Eduyn Albino","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"puerto-rico-john-arroyo","teamId":"puerto-rico","number":null,"name":"John Arroyo","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"puerto-rico-alexis-fuentes","teamId":"puerto-rico","number":null,"name":"Alexis Fuentes","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"puerto-rico-dwight-gaines","teamId":"puerto-rico","number":null,"name":"Dwight Gaines","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"puerto-rico-ivaniel-lopez","teamId":"puerto-rico","number":null,"name":"Ivaniel Lopez","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"puerto-rico-michael-portilla","teamId":"puerto-rico","number":null,"name":"Michael Portilla","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"puerto-rico-darrell-rodriguez","teamId":"puerto-rico","number":null,"name":"Darrell Rodriguez","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"puerto-rico-jomar-rodriguez","teamId":"puerto-rico","number":null,"name":"Jomar Rodriguez","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"puerto-rico-luis-rosado","teamId":"puerto-rico","number":null,"name":"Luis Rosado","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"puerto-rico-yaddiel-sanchez","teamId":"puerto-rico","number":null,"name":"Yaddiel Sanchez","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"puerto-rico-jodereck-torres","teamId":"puerto-rico","number":null,"name":"Jodereck Torres","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"puerto-rico-jeremy-willmore","teamId":"puerto-rico","number":null,"name":"Jeremy Willmore","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"serbia-aleksandar-asceric","teamId":"serbia","number":null,"name":"Aleksandar Asceric","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"serbia-viktor-babic","teamId":"serbia","number":null,"name":"Viktor Babic","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"serbia-petar-bjelica","teamId":"serbia","number":null,"name":"Petar Bjelica","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"serbia-danilo-bubanja","teamId":"serbia","number":null,"name":"Danilo Bubanja","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"serbia-filip-djurasinovic","teamId":"serbia","number":null,"name":"Filip Djurasinovic","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"serbia-nikola-djurovic","teamId":"serbia","number":null,"name":"Nikola Djurovic","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"serbia-uros-dramicanin","teamId":"serbia","number":null,"name":"Uros Dramicanin","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"serbia-luka-galic","teamId":"serbia","number":null,"name":"Luka Galic","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"serbia-jovan-ilic","teamId":"serbia","number":null,"name":"Jovan Ilic","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"serbia-luka-janjusevic","teamId":"serbia","number":null,"name":"Luka Janjusevic","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"serbia-nikola-kusturica","teamId":"serbia","number":null,"name":"Nikola Kusturica","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"serbia-matija-lukic","teamId":"serbia","number":null,"name":"Matija Lukic","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"serbia-luka-miladinovic","teamId":"serbia","number":null,"name":"Luka Miladinovic","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"serbia-lazar-milicic","teamId":"serbia","number":null,"name":"Lazar Milicic","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"serbia-filip-pavlovic","teamId":"serbia","number":null,"name":"Filip Pavlovic","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"serbia-luka-pavlovic","teamId":"serbia","number":null,"name":"Luka Pavlovic","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"serbia-veljko-petrovic","teamId":"serbia","number":null,"name":"Veljko Petrovic","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"serbia-vasa-saponjic","teamId":"serbia","number":null,"name":"Vasa Saponjic","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"serbia-ognjen-simjanovski","teamId":"serbia","number":null,"name":"Ognjen Simjanovski","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"serbia-vuk-stepanovic","teamId":"serbia","number":null,"name":"Vuk Stepanovic","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"serbia-filip-stevic","teamId":"serbia","number":null,"name":"Filip Stevic","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"serbia-marko-veselinovic","teamId":"serbia","number":null,"name":"Marko Veselinovic","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"slovenia-maks-anderlic","teamId":"slovenia","number":null,"name":"Maks Anderlic","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"slovenia-miha-gasperlin","teamId":"slovenia","number":null,"name":"Miha Gasperlin","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"slovenia-hugo-rene-godec","teamId":"slovenia","number":null,"name":"Hugo Rene Godec","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"slovenia-rok-ilic","teamId":"slovenia","number":null,"name":"Rok Ilic","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"slovenia-lun-jarc","teamId":"slovenia","number":null,"name":"Lun Jarc","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"slovenia-jaka-jovanovic","teamId":"slovenia","number":null,"name":"Jaka Jovanovic","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"slovenia-danijel-lipovac","teamId":"slovenia","number":null,"name":"Danijel Lipovac","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"slovenia-andrej-marinkovic","teamId":"slovenia","number":null,"name":"Andrej Marinkovic","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"slovenia-bor-ogorevic","teamId":"slovenia","number":null,"name":"Bor Ogorevic","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"slovenia-aleks-pejic-rupnik","teamId":"slovenia","number":null,"name":"Aleks Pejic Rupnik","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"slovenia-nejc-pirnat","teamId":"slovenia","number":null,"name":"Nejc Pirnat","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"slovenia-bine-pregl","teamId":"slovenia","number":null,"name":"Bine Pregl","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"slovenia-matic-rezec","teamId":"slovenia","number":null,"name":"Matic Rezec","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"slovenia-nejc-roznik","teamId":"slovenia","number":null,"name":"Nejc Roznik","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"slovenia-nejc-slapnik","teamId":"slovenia","number":null,"name":"Nejc Slapnik","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"slovenia-maj-strle","teamId":"slovenia","number":null,"name":"Maj Strle","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"slovenia-jan-tomsic","teamId":"slovenia","number":null,"name":"Jan Tomsic","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"slovenia-martin-trsan","teamId":"slovenia","number":null,"name":"Martin Trsan","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"slovenia-jakob-siftar","teamId":"slovenia","number":null,"name":"Jakob Siftar","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"turkiye-atahan-agacdelen","teamId":"turkiye","number":null,"name":"Atahan Agacdelen","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"turkiye-sarp-kaya-arda","teamId":"turkiye","number":null,"name":"Sarp Kaya Arda","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"turkiye-ethem-aras-atli","teamId":"turkiye","number":null,"name":"Ethem Aras Atli","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"turkiye-kaan-belgutay","teamId":"turkiye","number":null,"name":"Kaan Belgutay","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"turkiye-besir-briant","teamId":"turkiye","number":null,"name":"Besir Briant","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"turkiye-kemal-batu-copur","teamId":"turkiye","number":null,"name":"Kemal Batu Copur","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"turkiye-omer-alp-elitas","teamId":"turkiye","number":null,"name":"Omer Alp Elitas","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"turkiye-emir-karabulut","teamId":"turkiye","number":null,"name":"Emir Karabulut","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"turkiye-darius-karutasu","teamId":"turkiye","number":null,"name":"Darius Karutasu","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"turkiye-omer-kutluay","teamId":"turkiye","number":null,"name":"Omer Kutluay","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"turkiye-ruzgar-opcun","teamId":"turkiye","number":null,"name":"Ruzgar Opcun","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"turkiye-arda-ozturk","teamId":"turkiye","number":null,"name":"Arda Ozturk","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"turkiye-demir-ozturk","teamId":"turkiye","number":null,"name":"Demir Ozturk","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"turkiye-mehmet-akif-ozturk","teamId":"turkiye","number":null,"name":"Mehmet Akif Ozturk","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"turkiye-kerem-sertakar","teamId":"turkiye","number":null,"name":"Kerem Sertakar","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"turkiye-omer-yusuf-sik","teamId":"turkiye","number":null,"name":"Omer Yusuf Sik","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"turkiye-kartal-bora-simsek","teamId":"turkiye","number":null,"name":"Kartal Bora Simsek","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"turkiye-noyan-tolan","teamId":"turkiye","number":null,"name":"Noyan Tolan","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"turkiye-emre-yazici","teamId":"turkiye","number":null,"name":"Emre Yazici","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"usa-beckham-black","teamId":"usa","number":null,"name":"Beckham Black","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"usa-joaquim-boumtje-boumtje","teamId":"usa","number":null,"name":"Joaquim Boumtje Boumtje","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"usa-navorro-bowman-jr","teamId":"usa","number":null,"name":"NaVorro Bowman Jr.","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"usa-mason-collins","teamId":"usa","number":null,"name":"Mason Collins","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"usa-jj-crawford","teamId":"usa","number":null,"name":"JJ Crawford","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"usa-erick-dampier-jr","teamId":"usa","number":null,"name":"Erick Dampier Jr.","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"usa-cayden-daughtry","teamId":"usa","number":null,"name":"Cayden Daughtry","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"usa-asa-montgomery","teamId":"usa","number":null,"name":"Asa Montgomery","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"usa-jordan-page","teamId":"usa","number":null,"name":"Jordan Page","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"usa-cj-rosser","teamId":"usa","number":null,"name":"CJ Rosser","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"usa-aj-williams","teamId":"usa","number":null,"name":"AJ Williams","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"usa-xavier-young","teamId":"usa","number":null,"name":"Xavier Young","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"venezuela-williams-anillo","teamId":"venezuela","number":null,"name":"Williams Anillo","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"venezuela-chris-echezuria","teamId":"venezuela","number":null,"name":"Chris Echezuria","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"venezuela-gregori-gavidia","teamId":"venezuela","number":null,"name":"Gregori Gavidia","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"venezuela-santiago-gines","teamId":"venezuela","number":null,"name":"Santiago Gines","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"venezuela-bryan-gomez","teamId":"venezuela","number":null,"name":"Bryan Gomez","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"venezuela-kevin-gutierrez","teamId":"venezuela","number":null,"name":"Kevin Gutierrez","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"venezuela-jesus-lopez","teamId":"venezuela","number":null,"name":"Jesus Lopez","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"venezuela-aaron-lujano","teamId":"venezuela","number":null,"name":"Aaron Lujano","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"venezuela-samuel-marcano","teamId":"venezuela","number":null,"name":"Samuel Marcano","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"venezuela-antony-medina","teamId":"venezuela","number":null,"name":"Antony Medina","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"venezuela-carlos-millan","teamId":"venezuela","number":null,"name":"Carlos Millan","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"venezuela-fabian-montalban","teamId":"venezuela","number":null,"name":"Fabian Montalban","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"venezuela-enzo-nash","teamId":"venezuela","number":null,"name":"Enzo Nash","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"venezuela-evys-nava","teamId":"venezuela","number":null,"name":"Evys Nava","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"venezuela-carlos-perez","teamId":"venezuela","number":null,"name":"Carlos Perez","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"venezuela-cristian-perez","teamId":"venezuela","number":null,"name":"Cristian Perez","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"venezuela-ezequiel-perez","teamId":"venezuela","number":null,"name":"Ezequiel Perez","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"venezuela-winder-ricaurte","teamId":"venezuela","number":null,"name":"Winder Ricaurte","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"venezuela-alejandro-rodriguez","teamId":"venezuela","number":null,"name":"Alejandro Rodriguez","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"venezuela-yolfran-salgado","teamId":"venezuela","number":null,"name":"Yolfran Salgado","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"venezuela-enmanuel-sarabia","teamId":"venezuela","number":null,"name":"Enmanuel Sarabia","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"venezuela-deiker-torres","teamId":"venezuela","number":null,"name":"Deiker Torres","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"venezuela-samuel-uzcategui","teamId":"venezuela","number":null,"name":"Samuel Uzcategui","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"venezuela-julio-vasquez","teamId":"venezuela","number":null,"name":"Julio Vasquez","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"venezuela-ricardo-villarroel","teamId":"venezuela","number":null,"name":"Ricardo Villarroel","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]},
    {"id":"venezuela-santiago-villavicencio","teamId":"venezuela","number":null,"name":"Santiago Villavicencio","pos":"","height":"","birthYear":null,"stats":{"gp":0,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"tpg":null,"fgPct":null,"tpPct":null,"ftPct":null},"gamelog":[]}
  ]
};
